### PR TITLE
Fix pipeline bug related to the rendering that's returned

### LINKED ISSUE #12: 🐛 Asserting visibility on page after asserting element fails
# Problem
Assuming a page like:
```html
<html>
  <body>
    <h1>Hello</h1>
    <p>Greetings from the internet.</p>
  </body>
</html>
```

A test like this fails in an unexpected way:
```elixir
start(conn, "/")                    # 1
|> assert_visible("Hello")          # 2
|> assert_visible("p", "Greetings") # 3
|> assert_visible("Hello")          # 4
```
```
Assertion with =~ failed
     code:  assert html =~ expected_html
     left:  "<p>Greetings from the internet.</p>"
     right: "Hello"
     stacktrace:
       line # 4
```

# Potential Solution
I would expect a test like above to pass, because I expect each assertion to be made in the context of the full, rendered page. However, the current design on the lib returns the rendered element when targeted...

### PR DESCRIPTION
**Pull request by iamvery**
[closes #12]

### CODE REVIEW

File: test/iamvery/phoenix/live_view/test_helpers_test.exs [hunk 1]
```diff
@@ -5,19 +5,22 @@ end
...
   def has_element?(:live, _, nil), do: true
   def follow_redirect(@html, :conn), do: {:ok, :live, @html}
   def follow_redirect(redirect, :conn), do: redirect
   def render(:live), do: @html
+  def render(:element), do: @element
   def render_click(:live), do: @html
+  def render_click(:element), do: @html
   def render_change(:form), do: @html
   def render_submit(:form), do: @html
   def assert_patch(:live, _), do: {:ok, :live, @html}
```
Comment (iamvery) [inline test/iamvery/phoenix/live_view/test_helpers_test.exs:26]: 🤔 All this crazy stubbing is getting difficult to reason about. Should probably consider using the real helpers. Not sure how best to set that up.

**Comment by iamvery** [comment]
✍️ This has continued to bite me. This needs to be merged. Hoping to have some time to work through some of the Issues in the project 🔜

File: test/iamvery/phoenix/live_view/test_helpers_test.exs (hunk 1 above)
Comment (iamvery) [reply test/iamvery/phoenix/live_view/test_helpers_test.exs]: Fixed. See #21
